import { createClient } from "@supabase/supabase-js";
import type { Company } from "@/lib/types";

export const FALLBACK_COMPANIES: Company[] = [
  {
    id: "1",
    name: "CrownVault",
    slug: "crownvault",
    tagline:
      "Exclusive, invite-only marketplace for premium watch dealers. Verified dealers trading authenticated luxury timepieces.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#3B82F6",
    color_secondary: "#EC4899",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS", "Framer Motion"],
    display_order: 1,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "2",
    name: "RevenuFlow",
    slug: "revenuflow",
    tagline:
      "AI-powered revenue management for short-term rentals. Dynamic pricing, market analytics, and demand forecasting.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#8B5CF6",
    color_secondary: "#06B6D4",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS", "AI/ML"],
    display_order: 2,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "3",
    name: "WeCare Drive",
    slug: "wecare-drive",
    tagline:
      "HIPAA-compliant medical supply delivery platform. Encrypted data, audit logging, role-based access, and AI-powered operations.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#1E40AF",
    color_secondary: "#3B82F6",
    tech_stack: ["Next.js", "TypeScript", "PostgreSQL", "NextAuth", "AWS S3", "OpenAI"],
    display_order: 3,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "4",
    name: "GeniusTestBoost",
    slug: "geniustestboost",
    tagline:
      "1-on-1 expert tutoring for SAT, ACT, and GRE standardized tests. Diagnostic testing, custom study plans, and live sessions.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#C9A84C",
    color_secondary: "#7C6CF0",
    tech_stack: ["Express.js", "Supabase", "Vanilla JS", "HTML/CSS"],
    display_order: 4,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "5",
    name: "Karbon Agency",
    slug: "karbonagency",
    tagline:
      "Meta & Instagram advertising built exclusively for sim racing businesses. Hyper-targeted campaigns that fill seats.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#ef4444",
    color_secondary: "#f97316",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS"],
    display_order: 5,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "6",
    name: "Alameda Hospice",
    slug: "alamedahospice",
    tagline:
      "Marketing website for Alameda Care Hospice with scroll-triggered animations, contact form, and CRM integration.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#10B981",
    color_secondary: "#34D399",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "GSAP", "Tailwind CSS"],
    display_order: 6,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "7",
    name: "KashFlow",
    slug: "kashflow",
    tagline:
      "B2B invoicing, quoting, and payment platform. Create professional invoices, track payments, and manage clients.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#6366F1",
    color_secondary: "#A78BFA",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "Stripe", "Tailwind CSS"],
    display_order: 7,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "8",
    name: "Sim Racing Leaderboards",
    slug: "s4m-leaderboard",
    tagline:
      "Multi-event racing leaderboard platform with real-time results, QR code check-in, and AI-powered event descriptions.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#F59E0B",
    color_secondary: "#EF4444",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "Twilio", "Claude AI"],
    display_order: 8,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "9",
    name: "SimsForHire",
    slug: "sim4hire",
    tagline:
      "Racing simulator rental and event company. Full-motion racing simulators for corporate events, parties, and activations.",
    description: "",
    image_url: "",
    live_url: "https://simsforhire.com/",
    color_primary: "#0EA5E9",
    color_secondary: "#7C3AED",
    tech_stack: ["Astro", "TypeScript", "Twilio", "Resend", "Tailwind CSS"],
    display_order: 9,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "10",
    name: "Greystone",
    slug: "greystone",
    tagline:
      "Event management and calendar platform with Google Calendar sync, email campaigns via Resend, and Twilio SMS notifications.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#475569",
    color_secondary: "#94A3B8",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "NextAuth", "Google APIs", "Twilio"],
    display_order: 10,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "11",
    name: "KarbonBot AI",
    slug: "karbonbotai",
    tagline:
      "AI chatbot platform with Telegram integration, Claude-powered conversations, and Stripe billing for subscription management.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#F43F5E",
    color_secondary: "#FB923C",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "Claude AI", "Telegram", "Stripe"],
    display_order: 11,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "12",
    name: "KleanHQ",
    slug: "kleanhq",
    tagline:
      "Cleaning service management platform with real-time job tracking, Stripe payments, and automated email notifications via Resend.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#14B8A6",
    color_secondary: "#22D3EE",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "Stripe", "Resend", "Tailwind CSS"],
    display_order: 12,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "13",
    name: "LevelCRM",
    slug: "levelcrm",
    tagline:
      "Full-featured CRM system with pipeline management, contact tracking, dark mode UI, and advanced filtering powered by shadcn/ui.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#7C3AED",
    color_secondary: "#A78BFA",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "shadcn/ui", "Tailwind CSS"],
    display_order: 13,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "14",
    name: "MailPulse",
    slug: "mailpulse",
    tagline:
      "Email tracking and analytics platform. Track opens, clicks, and engagement in real time with Stripe-powered subscription billing.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#E11D48",
    color_secondary: "#F97316",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "Stripe", "Tailwind CSS"],
    display_order: 14,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "15",
    name: "S4H Events Admin",
    slug: "s4h-admin",
    tagline:
      "Event administration portal for SimsForHire with AI-powered scheduling, Stripe invoicing, and PDF contract generation.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#0284C7",
    color_secondary: "#38BDF8",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "Claude AI", "Stripe", "PDF"],
    display_order: 15,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "16",
    name: "Horsepower for Heroes",
    slug: "horsepower-for-heroes",
    tagline:
      "Charity racing program connecting veterans with motorsport experiences. PDF certificate generation, email campaigns, and donor tracking.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#DC2626",
    color_secondary: "#FBBF24",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "React-PDF", "Resend", "Framer Motion"],
    display_order: 16,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "17",
    name: "TTMC",
    slug: "ttmc",
    tagline:
      "Members-only motorsport club platform with Stripe subscriptions, event registration, and a full component library built on shadcn/ui.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#1E293B",
    color_secondary: "#F59E0B",
    tech_stack: ["React", "Vite", "TypeScript", "TanStack Query", "Supabase", "Stripe"],
    display_order: 17,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "18",
    name: "My Little Genius Academy",
    slug: "mylittlegeniusacademy",
    tagline:
      "Educational platform for young learners with interactive GSAP animations, course catalogs, and a blazing-fast Astro static site.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#8B5CF6",
    color_secondary: "#F472B6",
    tech_stack: ["Astro", "TypeScript", "GSAP", "Tailwind CSS", "Swiper"],
    display_order: 18,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "19",
    name: "Widget System",
    slug: "widgets",
    tagline:
      "Embeddable widget component system built as a Turborepo monorepo. Shared packages, versioned releases, and plug-and-play UI widgets.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#059669",
    color_secondary: "#34D399",
    tech_stack: ["Turborepo", "TypeScript", "Tailwind CSS", "Changesets"],
    display_order: 19,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "20",
    name: "LinkFlow",
    slug: "linkflow",
    tagline:
      "Automated SEO content syndication engine. AI-generated articles with natural backlinks distributed across 50+ platforms — replacing $3K/month agency retainers.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#0F172A",
    color_secondary: "#38BDF8",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "Stripe", "xAI Grok", "Resend"],
    display_order: 20,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
  {
    id: "21",
    name: "AutoApply",
    slug: "autoapply",
    tagline:
      "Automated job application platform that generates tailored resumes and cover letters, tracks applications, and streamlines the job search.",
    description: "",
    image_url: "",
    live_url: "",
    color_primary: "#2563EB",
    color_secondary: "#60A5FA",
    tech_stack: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS"],
    display_order: 21,
    is_featured: true,
    created_at: "",
    updated_at: "",
  },
];

export async function getCompanies(): Promise<Company[]> {
  try {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
    if (!url || !key) return FALLBACK_COMPANIES;

    const supabase = createClient(url, key, {
      global: { fetch: (input, init) => fetch(input, { ...init, cache: "no-store" }) },
    });
    const { data, error } = await supabase
      .from("companies")
      .select("*")
      .eq("is_featured", true)
      .order("display_order", { ascending: true });

    if (error || !data || data.length === 0) return FALLBACK_COMPANIES;
    return data as Company[];
  } catch {
    return FALLBACK_COMPANIES;
  }
}

export async function getCompanyBySlug(slug: string): Promise<Company | null> {
  const companies = await getCompanies();
  return companies.find((c) => c.slug === slug) || null;
}
